#1.Importing Libraries


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


#2.Importing data

In [ ]:
df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Car%20Price.csv')


In [ ]:
df.head()

Brand                     Model  Year  Selling_Price  KM_Driven    Fuel  \
0   Maruti             Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2  Hyundai      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3   Datsun    Datsun RediGO T Option  2017         250000      46000  Petrol   
4    Honda     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  Seller_Type Transmission         Owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Brand          4340 non-null   object
 1   Model          4340 non-null   object
 2   Year           4340 non-null   int64 
 3   Selling_Price  4340 non-null   int64 
 4   KM_Driven      4340 non-null   int64 
 5   Fuel           4340 non-null   object
 6   Seller_Type    4340 non-null   object
 7   Transmission   4340 non-null   object
 8   Owner          4340 non-null   object
dtypes: int64(3), object(6)
memory usage: 305.3+ KB


In [ ]:
df.describe()

Year  Selling_Price      KM_Driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [ ]:
df

Brand                                Model  Year  Selling_Price  \
0      Maruti                        Maruti 800 AC  2007          60000   
1      Maruti             Maruti Wagon R LXI Minor  2007         135000   
2     Hyundai                 Hyundai Verna 1.6 SX  2012         600000   
3      Datsun               Datsun RediGO T Option  2017         250000   
4       Honda                Honda Amaze VX i-DTEC  2014         450000   
...       ...                                  ...   ...            ...   
4335  Hyundai  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999   
4336  Hyundai           Hyundai i20 Magna 1.4 CRDi  2014         409999   
4337   Maruti                  Maruti 800 AC BSIII  2009         110000   
4338  Hyundai     Hyundai Creta 1.6 CRDi SX Option  2016         865000   
4339  Renault                     Renault KWID RXT  2016         225000   

      KM_Driven    Fuel Seller_Type Transmission         Owner  
0         70000  Petrol  Individual       Manual   First Owner  
1         50000  Petrol  Individual       Manual   First Owner  
2        100000  Diesel  Individual       Manual   First Owner  
3         46000  Petrol  Individual       Manual   First Owner  
4        141000  Diesel  Individual       Manual  Second Owner  
...         ...     ...         ...          ...           ...  
4335      80000  Diesel  Individual       Manual  Second Owner  
4336      80000  Diesel  Individual       Manual  Second Owner  
4337      83000  Petrol  Individual       Manual  Second Owner  
4338      90000  Diesel  Individual       Manual   First Owner  
4339      40000  Petrol  Individual       Manual   First Owner  

[4340 rows x 9 columns]

In [ ]:
df.tail()

Brand                                Model  Year  Selling_Price  \
4335  Hyundai  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999   
4336  Hyundai           Hyundai i20 Magna 1.4 CRDi  2014         409999   
4337   Maruti                  Maruti 800 AC BSIII  2009         110000   
4338  Hyundai     Hyundai Creta 1.6 CRDi SX Option  2016         865000   
4339  Renault                     Renault KWID RXT  2016         225000   

      KM_Driven    Fuel Seller_Type Transmission         Owner  
4335      80000  Diesel  Individual       Manual  Second Owner  
4336      80000  Diesel  Individual       Manual  Second Owner  
4337      83000  Petrol  Individual       Manual  Second Owner  
4338      90000  Diesel  Individual       Manual   First Owner  
4339      40000  Petrol  Individual       Manual   First Owner

#3 Getting count of each attributes

In [ ]:
df[['Brand']].value_counts()

Brand        
Maruti           1280
Hyundai           821
Mahindra          365
Tata              361
Honda             252
Ford              238
Toyota            206
Chevrolet         188
Renault           146
Volkswagen        107
Skoda              68
Nissan             64
Audi               60
BMW                39
Fiat               37
Datsun             37
Mercedes-Benz      35
Mitsubishi          6
Jaguar              6
Land                5
Ambassador          4
Volvo               4
Jeep                3
OpelCorsa           2
MG                  2
Isuzu               1
Force               1
Daewoo              1
Kia                 1
dtype: int64

In [ ]:
df[['Fuel']].value_counts()

Fuel    
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
dtype: int64

In [ ]:
df[['Model']].value_counts()


Model                               
Maruti Swift Dzire VDI                  69
Maruti Alto 800 LXI                     59
Maruti Alto LXi                         47
Hyundai EON Era Plus                    35
Maruti Alto LX                          35
                                        ..
Mahindra KUV 100 G80 K4 Plus             1
Mahindra KUV 100 mFALCON D75 K8          1
Mahindra KUV 100 mFALCON D75 K8 AW       1
Mahindra KUV 100 mFALCON G80 K2 Plus     1
Volvo XC60 D5 Inscription                1
Length: 1491, dtype: int64

In [ ]:
df[['Seller_Type']].value_counts()

Seller_Type     
Individual          3244
Dealer               994
Trustmark Dealer     102
dtype: int64

In [ ]:
df[['Transmission']].value_counts()

Transmission
Manual          3892
Automatic        448
dtype: int64

In [ ]:
df[['Owner']].value_counts()

Owner               
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
dtype: int64

#4 Getting column names

In [ ]:
df.columns

Index(['Brand', 'Model', 'Year', 'Selling_Price', 'KM_Driven', 'Fuel',
       'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [ ]:
df.shape

(4340, 9)

In [ ]:
df.replace({'Fuel':{'Petrol':0,'Diesel':1,'CNG':2,'LPG':3,'Electric':4}},inplace=True)

In [ ]:
df.replace({'Seller_Type':{'Individual':0,'Dealer':1,'Trustmark Dealer':2}},inplace=True)

In [ ]:
df.replace({'Owner':{'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth & Above Owner':3,'Test Drive Car':4}},inplace=True)

In [ ]:
df.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

#3.Defining target variables and features


In [ ]:
y=df['Selling_Price']

In [ ]:
y.shape

(4340,)

In [ ]:
X=df.drop(['Brand','Model','Selling_Price'],axis=1)

In [ ]:
X

Year  KM_Driven  Fuel  Seller_Type  Transmission  Owner
0     2007      70000     0            0             0      0
1     2007      50000     0            0             0      0
2     2012     100000     1            0             0      0
3     2017      46000     0            0             0      0
4     2014     141000     1            0             0      1
...    ...        ...   ...          ...           ...    ...
4335  2014      80000     1            0             0      1
4336  2014      80000     1            0             0      1
4337  2009      83000     0            0             0      1
4338  2016      90000     1            0             0      0
4339  2016      40000     0            0             0      0

[4340 rows x 6 columns]

#4.Train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=2529)

In [ ]:
X_train

Year  KM_Driven  Fuel  Seller_Type  Transmission  Owner
903   2017      19890     0            1             1      0
4134  2015      90000     1            0             0      0
659   2008     100000     1            0             0      3
3161  2016      23000     0            1             0      1
2993  2018      25000     0            0             0      0
...    ...        ...   ...          ...           ...    ...
2957  2006     120000     0            0             0      1
2341  2016      20000     0            0             0      0
1576  2017      60000     0            0             0      0
3656  2016      65000     1            0             0      0
2876  2017      37000     0            0             0      0

[3038 rows x 6 columns]

#5.Model Selection

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()

# 6.Activating mode i.e fitting the model

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
lr.intercept_


-79077633.31945786

In [ ]:
lr.coef_

array([ 3.94417166e+04, -6.64593455e-01,  2.16545736e+05,  9.39824076e+04,
        8.80742969e+05, -1.40664270e+04])

#7.Predicting

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
X_mytest=[[2007,70000,0,0,0,0]]

In [ ]:
lr.predict(X_mytest)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([35370.27293821])

In [ ]:
y_mypred

array([35370.27293821])

In [ ]:
y_pred

array([502458.82786413, 646333.17428704, 521962.74075836, ...,
       620183.32683781, 315403.8278857 , 731862.54196037])

#8.Finding Accuracy

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_squared_error(y_test,y_pred)

193242972302.19553

In [ ]:
mean_absolute_error(y_test,y_pred)

228808.95522977872

In [ ]:
r2_score(y_test,y_pred)

0.4075563394370839